baseURL: https://k8s.services
title: Kubernetes Services
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: cns-logo.png
    link: /
    # Default width/height. Uncomment if you need to change
    width: 178
    #height: 56
  font:
    name: "Clarity City"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Kubernetes design, deployment, and management
    # Hero subtitle (optional)
    subtitle: Adopt powerful cloud solutions to improve efficiency, boost revenue, and create a scalable business.
    # Button text
    buttontext: Become our client
    # Where the main hero button links to
    buttonlink: "#contact"
    # Hero image (from static/images/___)
    image: k8s-logo.png

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Services
    url: /#services
  - title: About Us
    url: https://cloudnativesolutions.ro
  - title: Contact Us
    url: /#contact
    button: true
  services:
    title: Our Services
    subtitle: with great responsibility
    tiles:
    - title: Kubernetes management
      icon: mouse-globe
      text: We offer organizations support for deploying, operating, maintaining and upgrading Kubernetes clusters.
      url: /
      buttonText: Get started
    - title: Automated deployments
      icon: laptop-cloud
      text:  Streamline application development, reducing deployment time, ensuring consistency, and increasing agility.
      url: /
      buttonText: More info
    - title: Cloud migration
      icon: plug-cloud
      text: Move your workloads and data to the cloud, minimizing downtime and ensuring a seamless transition to a new cloud environment.
      url: /
      buttonText: More info
  section3:
    title: One platform
    subtitle: To rule them all
    image: kubernetes.png
    buttonText: Get started
    buttonLink: "#contact"
  contact:
    title: Contact Us
    subtitle: We'd love to hear from you
    buttonText: Send Message
    action: https://formspree.io/f/xeqwqllj
    method: POST
  footer:
    # Logo (from /images/logos/___)
    logo: cns-logo.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/cloudnative-solutions
      # Icons are from Font Awesome
      icon: github
    - link: https://linkedin.com/company/cloudnative-solutions
      icon: linkedin
    - link: https://facebook.com/CloudNativeSolutions
      icon: facebook
    - link: https://twitter.com/CNS_RO
      icon: twitter
    - link: https://cloudnativesolutions.ro
      icon: globe
    quicklinks:
      column1:
        title: "SITE"
        links:
        - text: Services
          link: /#services
        - text: About Us
          link: https://cloudnativesolutions.ro
        - text: Contact Us
          link: /#contact
